workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Récupérer les dépendances Flutter
        script: |
          flutter packages pub get
      - name: Analyser le code (optionnel)
        script: |
          flutter analyze
      - name: Builder l'APK Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
